// <auto-generated />
using ECommerceApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApplication.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = " 7+ Specialized Nutrition Drink Powder",
                            ImageUrl = "https://m.media-amazon.com/images/I/71FM2dBCaVL._AC_UL320_.jpg",
                            Price = 390.9m,
                            Title = "Pediasure0g"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Health & Nutrition Drink for Toddlers & Young Kids",
                            ImageUrl = "https://m.media-amazon.com/images/I/61ptL7H+M4L._AC_UL320_.jpg",
                            Price = 444.9m,
                            Title = "Junior Horlicks"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Kellogg's Chocos Moons & Stars 1.2kg with Whole Grain",
                            ImageUrl = "https://m.media-amazon.com/images/I/61hm-b9tZ9L._AC_UL320_.jpg",
                            Price = 399.0m,
                            Title = "Kellogg's Chocos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
